### ISSUE TITLE
Offset for Downlight Brightness

### ISSUE THREAD

**Issue by Cayn183** [florianL21/LED-ClockShelf#12]
Hey,

i thanks a lot for the nice code, which you/r have wrote.
I have invested many hours to get your code to work on my installed clock. had to modified to 24h format, 0 off in the higher hour digit and many more.... 
So i hope you can help me and give me the solution, that i not have to search many other hours for it.

I want to get a offset to get the Brightness of the Downlight brighter. is there any point which i can insert it in the code whichout to modify anything?

Best regards.
Cayn183

**Comment by florianL21** [comment]
Hello,
So what exactly are you trying to do? Having the time Displayed in a 24h format? If so I already have a configuration that you could use as a base here: https://github.com/florianL21/LED-ClockShelf/blob/master/lib/LED_clock/Config/Setup/clock-only/DisplayConfiguration.cpp

I documented how to adjust this configuration here: https://giant-led-clock.readthedocs.io/en/master/sites/GeneralConfiguration.html#display-configuration

As for the offset for the downlighters, this is sadly not so easy since the brightness is currently set globally for all LEDs. So I see no easy was of adjusting this for now

**Comment by Cayn183** [comment]
Thanks, for the reply, i have coded the for me matching 24h format, i build a special clock because i had not enough space.

"As for the offset for the downlighters, this is sadly not so easy since the brightness is currently set globally for all LEDs. So I see no easy was of adjusting this for now"

Thanks, i tried myself...but have seen its not easy^^
